# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPolicy',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=40, unique=True)),
                ('policy_description', models.CharField(max_length=4096, null=True)),
            ],
            options={
                'db_table': 'config_policy',
            },
        ),
        migrations.CreateModel(
            name='ConfigPolicyRule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('eval_expression', models.CharField(max_length=4096)),
                ('policy', models.ForeignKey(db_column='policy_id', on_delete=django.db.models.deletion.CASCADE, to='config_policy.ConfigPolicy')),
            ],
            options={
                'db_table': 'config_policy_rule',
            },
        ),
        migrations.CreateModel(
            name='ConfigPolicyScheme',
            fields=[
                ('scheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheme_name', models.CharField(max_length=40)),
                ('scheme_type', models.CharField(max_length=40)),
                ('scheme_description', models.CharField(max_length=4096, null=True)),
                ('policy', models.ForeignKey(db_column='policy_id', on_delete=django.db.models.deletion.CASCADE, to='config_policy.ConfigPolicy')),
            ],
            options={
                'db_table': 'config_policy_scheme',
            },
        ),
        migrations.AlterUniqueTogether(
            name='configpolicyscheme',
            unique_together=set([('scheme_id', 'policy')]),
        ),
    ]
